version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "8081:5432"

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "deywesonalm@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "0512"
    ports:
      - "54321:80"
    depends_on:
      - postgres